imports

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Load dataset

In [2]:
df = pd.read_csv('./dirty_data.csv')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 320 entries, 0 to 319
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   CustomerID   286 non-null    float64
 1   Age          284 non-null    object
 2   Income       285 non-null    object
 3   City         287 non-null    object
 4   Signup_Date  286 non-null    object
 5   Purchased    288 non-null    object
dtypes: float64(1), object(5)
memory usage: 15.1+ KB

In [4]:
df.head(40)

    CustomerID      Age     Income         City Signup_Date Purchased
0       1001.0  unknown   27971.68      Houston  2022-01-01        No
1       1002.0     45yo   62015.76      Chicago  2022-01-02        No
2       1003.0       89   31728.49  Los Angeles  2022-01-03       yes
3       1004.0       78    47342.6     New York  2022-01-04       NaN
4       1005.0       38        NaN      Phoenix  2022-01-05       yes
5       1006.0      250    57930.2      Houston  2022-01-06        No
6       1007.0       20      -5000  Los Angeles  2022-01-07       Yes
7       1008.0       39   53083.98  Los Angeles  2022-01-08        No
8       1009.0      NaN        NaN      Chicago         NaN        No
9       1010.0       19        NaN      Chicago  2022-01-10       NaN
10      1011.0      NaN   36998.02      Phoenix  2022-01-11        No
11         NaN       55   73020.71      Phoenix  2022-01-12       Yes
12      1013.0       19   57247.51     New York         NaN        No
13      1014.0       81   57113.61          NaN         NaN        no
14      1015.0       77   60316.29      Phoenix  2022-01-15       NaN
15      1016.0      NaN   26795.31      Phoenix  2022-01-16        No
16      1017.0       50   69495.88      Houston         NaN        No
17      1018.0       75   47335.83      Chicago  2022-01-18        No
18      1019.0       39  $73155.98     New York  2022-01-19        No
19      1020.0       66   52731.46      Chicago  2022-01-20        no
20      1021.0       76   49382.18      Chicago  2022-01-21       Yes
21      1022.0       59        NaN      Phoenix  2022-01-22       NaN
22      1023.0       77   43517.36      Houston  2022-01-23        No
23      1024.0       32  $61334.71  Los Angeles  2022-01-24        No
24      1025.0       79   35381.29      Houston  2022-01-25       Yes
25      1026.0       79   25141.01      Houston  2022-01-26       Yes
26      1027.0       64  $42136.77          NaN  2022-01-27        No
27      1028.0       79   67600.08      Houston  2022-01-28       NaN
28         NaN       68   81719.37     New York  2022-01-29        no
29      1030.0       72   44838.76      Chicago  2022-01-30       Yes
30      1031.0       81   31767.57    New York   2022-01-31       Yes
31      1032.0       20   49853.06          NaN  2022-02-01       Yes
32      1033.0       68   57757.83      Chicago  2022-02-02        No
33      1034.0       24   63668.46  Los Angeles  2022-02-03       yes
34      1035.0       38   87019.62      Chicago  2022-02-04       NaN
35      1036.0       56   58402.73      Phoenix  2022-02-05       Yes
36      1037.0       35   79831.92      Houston  2022-02-06        No
37      1038.0       21   48056.12      Phoenix  2022-02-07        no
38      1039.0       77   56298.49  Los Angeles  2022-02-08        No
39      1040.0       31   46106.76      Houston  2022-02-09       Yes

Get the unique values in all columns

In [5]:
for col in df.columns:
    print(f"Unique values in column '{col}': {df[col].unique()}\n")

Unique values in column 'CustomerID': [1001. 1002. 1003. 1004. 1005. 1006. 1007. 1008. 1009. 1010. 1011.   nan
 1013. 1014. 1015. 1016. 1017. 1018. 1019. 1020. 1021. 1022. 1023. 1024.
 1025. 1026. 1027. 1028. 1030. 1031. 1032. 1033. 1034. 1035. 1036. 1037.
 1038. 1039. 1040. 1041. 1042. 1044. 1045. 1046. 1047. 1048. 1049. 1050.
 1051. 1052. 1053. 1055. 1056. 1057. 1058. 1059. 1062. 1063. 1064. 1065.
 1066. 1067. 1068. 1070. 1071. 1072. 1073. 1074. 1075. 1076. 1077. 1078.
 1080. 1081. 1083. 1086. 1087. 1088. 1089. 1090. 1091. 1092. 1093. 1094.
 1095. 1097. 1099. 1100. 1101. 1102. 1103. 1104. 1105. 1107. 1108. 1109.
 1110. 1111. 1112. 1113. 1116. 1117. 1118. 1119. 1120. 1121. 1122. 1123.
 1124. 1125. 1126. 1127. 1128. 1129. 1130. 1131. 1132. 1133. 1136. 1137.
 1138. 1139. 1140. 1141. 1142. 1143. 1144. 1146. 1147. 1148. 1149. 1150.
 1151. 1152. 1153. 1154. 1155. 1156. 1157. 1158. 1159. 1160. 1161. 1162.
 1163. 1164. 1165. 1166. 1167. 1168. 1169. 1170. 1171. 1172. 1173. 1174.
 1175. 1176. 1177. 1178. 1179. 1180. 1181. 1182. 1183. 1184. 1185. 1186.
 1188. 1189. 1190. 1191. 1192. 1193. 1194. 1195. 1196. 1197. 1199. 1200.
 1201. 1202. 1203. 1204. 1205. 1206. 1207. 1208. 1210. 1211. 1213. 1214.
 1215. 1216. 1217. 1219. 1220. 1221. 1223. 1224. 1225. 1226. 1227. 1228.
 1229. 1230. 1232. 1233. 1234. 1235. 1236. 1238. 1239. 1240. 1241. 1242.
 1243. 1244. 1245. 1246. 1247. 1248. 1249. 1251. 1252. 1253. 1254. 1255.
 1256. 1257. 1258. 1259. 1260. 1262. 1263. 1264. 1265. 1266. 1267. 1268.
 1269. 1270. 1271. 1272. 1273. 1274. 1275. 1276. 1277. 1278. 1280. 1281.
 1282. 1283. 1284. 1285. 1286. 1287. 1288. 1290. 1291. 1292. 1293. 1294.
 1295. 1296. 1297. 1299. 1300.]

Unique values in column 'Age': ['unknown' '45yo' '89' '78' '38' '250' '20' '39' nan '19' '55' '81' '77'
 '50' '75' '66' '76' '59' '32' '79' '64' '68' '72' '24' '56' '35' '21'
 '31' '26' '70' '88' '61' '25' '52' '53' '67' '23' '71' '80' '51' '65'
 '57' '41' '58' '46' '62' '82' '18' '28' '22' '45' '40' '54' '44' '69'
 '60' '30' '49' '83' '74' '47' '87' '29' '73' '36' '85' '34' '86' '33'
 '37' '48' '42' '84' '63']

Unique values in column 'Income': ['27971.68' '62015.76' '31728.49' '47342.6' nan '57930.2' '-5000'
 '53083.98' '36998.02' '73020.71' '57247.51' '57113.61' '60316.29'
 '26795.31' '69495.88' '47335.83' '$73155.98' '52731.46' '49382.18'
 '43517.36' '$61334.71' '35381.29' '25141.01' '$42136.77' '67600.08'
 '81719.37' '44838.76' '31767.57' '49853.06' '57757.83' '63668.46'
 '87019.62' '58402.73' '79831.92' '48056.12' '56298.49' '46106.76'
 '44799.93' '51048.91' '50790.18' '45940.36' '$46761.21' '71451.94'
 '86696.68' '47523.9' '50134.07' '62869.14' '$102805.5' '56262.45'
 '69589.49' '78167.12' '60161.02' '68893.49' '64117.58' '70487.69'
 '39483.96' '58064.24' '62218.27' '72055.26' '61703.35' '37825.77'
 '$63869.74' '41753.82' '44509.33' '48722.37' '53328.72' '31844.12'
 '71753.4' '37667.26' '78551.66' '38125.72' '74228.81' '54573.68'
 '29253.63' '39355.58' '74897.08' '61729.73' '21748.58' '75843.5'
 '83056.36' '45771.32' '60741.99' '62382.12' '32088.21' '57707.39'
 '71065.62' '66467.17' '38332.54' '42060.77' '66858.91' '21187.62'
 '$53852.02' '46155.21' '50525.48' '48830.64' '69760.35' '56553.52'
 '59014.54' '34865.31' '4538.57' '71853.13' '87148.08' '49861.17'
 '58739.72' '59867.77' '80129.4' '68334.76' '62440.96' '55903.49'
 '33408.08' '49247.69' '51494.45' '55665.26' '37358.09' '33073.65'
 '59348.24' '52191.63' '28850.72' '71042.17' '52542.02' '82911.67'
 '77173.78' '41807.98' '31203.05' '$48667.34' '76656.21' '26276.39'
 '67779.17' '66525.09' '63320.39' '65997.6' '38436.67' '46761.13'
 '18112.1' '55861.19' '$42338.38' '75382.25' '50704.8' '55684.12'
 '60837.69' '50988.99' '53442.38' '67653.61' '39005.18' '44472.8'
 '40493.33' '76551.32' '44474.5' '52850.75' '45990.93' '61940.86'
 '39387.25' '34713.24' '46623.69' '43026.47' '34932.33' '50149.41'
 '30098.24' '80916.21' '32610.98' '45305.51' '48946.68' '80270.27'
 '29045.27' '70557.38' '50353.85' '37452.74' '53380.23' '77906.52'
 '45763.21' '76542.75' '58880.0' '73487.71' '58280.25' '47734.36'
 '57496.44' '67113.33' '$68862.29' '67192.85' '34739.17' '45441.47'
 '45152.07' '43313.8' '41918.44' '60039.23' '48609.51' '74131.95'
 '53626.51' '69056.09' '46460.11' '61205.69' '15868.18' '45173.72'
 '63906.13' '73192.23' '55743.59' '79158.68' '74109.9' '41971.27'
 '56746.16' '60402.54' '80778.99' '67991.06' '53446.36' '58301.11'
 '$26741.75' '69529.43' '64685.99' '73182.35' '52839.26' '56920.62'
 '47779.92' '37779.18' '45966.16' '27710.49' '68719.08' '22376.76'
 '28538.1' '77498.33' '63415.5' '43713.3' '80106.22' '55655.54' '71105.23'
 '56140.72' '60294.4' '64241.6' '47069.14' '35795.63' '55762.64' '47670.4'
 '22812.15' '36722.66' '37595.12' '54375.61' '41498.27' '56837.58'
 '$84601.91' '49314.14' '$39106.31' '57722.6' '43371.52' '55356.27'
 '59734.54' '54472.05' '55848.38' '57881.36' '56911.52' '68002.74'
 '62065.55' '$49626.86' '68527.95' '41931.3' '51598.76' '43433.7'
 '63642.62' '72844.0' '58350.04' '56128.99' '41874.87' '44461.73'
 '37101.1' '22349.78' '49134.49' '50528.42' '87592.63' '78442.2' '63334.6'
 '86267.16' '75863.55' '$67991.06' '68862.29' '$50353.85' '$46460.11']

Unique values in column 'City': ['Houston' 'Chicago' 'Los Angeles' 'New York' 'Phoenix' nan ' New York '
 ' Chicago ' ' Phoenix ' ' Houston ' ' Los Angeles ']

Unique values in column 'Signup_Date': ['2022-01-01' '2022-01-02' '2022-01-03' '2022-01-04' '2022-01-05'
 '2022-01-06' '2022-01-07' '2022-01-08' nan '2022-01-10' '2022-01-11'
 '2022-01-12' '2022-01-15' '2022-01-16' '2022-01-18' '2022-01-19'
 '2022-01-20' '2022-01-21' '2022-01-22' '2022-01-23' '2022-01-24'
 '2022-01-25' '2022-01-26' '2022-01-27' '2022-01-28' '2022-01-29'
 '2022-01-30' '2022-01-31' '2022-02-01' '2022-02-02' '2022-02-03'
 '2022-02-04' '2022-02-05' '2022-02-06' '2022-02-07' '2022-02-08'
 '2022-02-09' '2022-02-10' '2022-02-11' '2022-02-12' '2022-02-14'
 '2022-02-15' '2022-02-16' '2022-02-17' '2022-02-18' '2022-02-19'
 '2022-02-20' '2022-02-21' '2022-02-22' '2022-02-23' '2022-02-24'
 '2022-02-25' '2022-02-26' '2022-02-27' '2022-02-28' '2022-03-01'
 '2022-03-02' '2022-03-03' '2022-03-05' '2022-03-06' '2022-03-07'
 '2022-03-08' '2022-03-09' '2022-03-10' '2022-03-11' '2022-03-12'
 '2022-03-13' '2022-03-14' '2022-03-15' '2022-03-16' '2022-03-17'
 '2022-03-18' '2022-03-19' '2022-03-20' '2022-03-21' '2022-03-22'
 '2022-03-23' '2022-03-24' '2022-03-25' '2022-03-26' '2022-03-27'
 '2022-03-28' '2022-03-29' '2022-03-30' '2022-03-31' '2022-04-01'
 '2022-04-02' '2022-04-03' '2022-04-04' '2022-04-05' '2022-04-06'
 '2022-04-07' '2022-04-08' '2022-04-09' '2022-04-10' '2022-04-11'
 '2022-04-12' '2022-04-13' '2022-04-14' '2022-04-15' '2022-04-17'
 '2022-04-18' '2022-04-19' '2022-04-20' '2022-04-21' '2022-04-23'
 '2022-04-24' '2022-04-25' '2022-04-26' '2022-04-27' '2022-04-28'
 '2022-04-29' '2022-04-30' '2022-05-01' '2022-05-02' '2022-05-03'
 '2022-05-05' '2022-05-06' '2022-05-07' '2022-05-08' '2022-05-10'
 '2022-05-11' '2022-05-12' '2022-05-13' '2022-05-14' '2022-05-15'
 '2022-05-16' '2022-05-17' '2022-05-18' '2022-05-19' '2022-05-21'
 '2022-05-23' '2022-05-24' '2022-05-26' '2022-05-27' '2022-05-28'
 '2022-05-29' '2022-05-31' '2022-06-01' '2022-06-02' '2022-06-04'
 '2022-06-05' '2022-06-06' '2022-06-09' '2022-06-10' '2022-06-11'
 '2022-06-12' '2022-06-13' '2022-06-14' '2022-06-15' '2022-06-16'
 '2022-06-17' '2022-06-18' '2022-06-19' '2022-06-20' '2022-06-21'
 '2022-06-22' '2022-06-23' '2022-06-24' '2022-06-25' '2022-06-26'
 '2022-06-27' '2022-06-28' '2022-06-29' '2022-06-30' '2022-07-02'
 '2022-07-03' '2022-07-04' '2022-07-05' '2022-07-06' '2022-07-07'
 '2022-07-08' '2022-07-09' '2022-07-10' '2022-07-11' '2022-07-12'
 '2022-07-13' '2022-07-14' '2022-07-15' '2022-07-17' '2022-07-18'
 '2022-07-20' '2022-07-22' '2022-07-23' '2022-07-25' '2022-07-27'
 '2022-07-28' '2022-07-29' '2022-07-30' '2022-07-31' '2022-08-01'
 '2022-08-02' '2022-08-03' '2022-08-04' '2022-08-05' '2022-08-06'
 '2022-08-07' '2022-08-08' '2022-08-09' '2022-08-11' '2022-08-12'
 '2022-08-13' '2022-08-14' '2022-08-15' '2022-08-17' '2022-08-18'
 '2022-08-19' '2022-08-20' '2022-08-21' '2022-08-22' '2022-08-23'
 '2022-08-24' '2022-08-25' '2022-08-26' '2022-08-27' '2022-08-29'
 '2022-08-30' '2022-08-31' '2022-09-01' '2022-09-02' '2022-09-03'
 '2022-09-04' '2022-09-05' '2022-09-07' '2022-09-08' '2022-09-09'
 '2022-09-10' '2022-09-11' '2022-09-12' '2022-09-13' '2022-09-14'
 '2022-09-15' '2022-09-16' '2022-09-17' '2022-09-18' '2022-09-19'
 '2022-09-20' '2022-09-21' '2022-09-22' '2022-09-23' '2022-09-24'
 '2022-09-25' '2022-09-26' '2022-09-27' '2022-09-28' '2022-09-29'
 '2022-10-01' '2022-10-02' '2022-10-03' '2022-10-04' '2022-10-06'
 '2022-10-07' '2022-10-09' '2022-10-10' '2022-10-11' '2022-10-12'
 '2022-10-13' '2022-10-14' '2022-10-16' '2022-10-17' '2022-10-18'
 '2022-10-19' '2022-10-20' '2022-10-21' '2022-10-22' '2022-10-23'
 '2022-10-24' '2022-10-25' '2022-10-27']

Unique values in column 'Purchased': ['No' 'yes' nan 'Yes' 'no']

Data contains certain values. cleanup needed.

In [6]:
error_values = ['unknown', 'nan']

for col in df.columns:

    if df[col].dtype == 'object':
        df[col] = df[col].str.strip().str.lower()

    # replace the error values with NaN
    df[col] = df[col].replace(error_values, pd.NA)
    if df[col].dtype == 'float64' or df[col].dtype == 'int64':
        df[col] = pd.to_numeric(df[col], errors='coerce')

In [7]:
df.head(20)

    CustomerID   Age     Income         City Signup_Date Purchased
0       1001.0  <NA>   27971.68      houston  2022-01-01        no
1       1002.0  45yo   62015.76      chicago  2022-01-02        no
2       1003.0    89   31728.49  los angeles  2022-01-03       yes
3       1004.0    78    47342.6     new york  2022-01-04       NaN
4       1005.0    38        NaN      phoenix  2022-01-05       yes
5       1006.0   250    57930.2      houston  2022-01-06        no
6       1007.0    20      -5000  los angeles  2022-01-07       yes
7       1008.0    39   53083.98  los angeles  2022-01-08        no
8       1009.0   NaN        NaN      chicago         NaN        no
9       1010.0    19        NaN      chicago  2022-01-10       NaN
10      1011.0   NaN   36998.02      phoenix  2022-01-11        no
11         NaN    55   73020.71      phoenix  2022-01-12       yes
12      1013.0    19   57247.51     new york         NaN        no
13      1014.0    81   57113.61          NaN         NaN        no
14      1015.0    77   60316.29      phoenix  2022-01-15       NaN
15      1016.0   NaN   26795.31      phoenix  2022-01-16        no
16      1017.0    50   69495.88      houston         NaN        no
17      1018.0    75   47335.83      chicago  2022-01-18        no
18      1019.0    39  $73155.98     new york  2022-01-19        no
19      1020.0    66   52731.46      chicago  2022-01-20        no